---
# tasks file for roles/tomcat
- name: Create the target folder
  file:
   path: /home/osgdev/ansiblehands/tomcat
   state: directory

- name: Install Tomcat
  unarchive:
   src: apache-tomcat-8.5.27.tar.gz
   dest: /home/osgdev/ansiblehands/tomcat 

- name: Configure the port address
  template: 
   src: server.xml.j2
   dest: /home/osgdev/ansiblehands/tomcat/apache-tomcat-8.5.27/conf/server.xml

- name: Deploy the war file in the Webapps directory
  copy:
   src: ILP-0.0.1-20190411.192309-16.war
   dest: /home/osgdev/ansiblehands/tomcat/apache-tomcat-8.5.27/webapps

- name: Start the tomcat server
  shell: /home/osgdev/ansiblehands/tomcat/apache-tomcat-8.5.27/bin/startup.sh  
  
